### ISSUE TITLE
Missing dialogmaster.h

### ISSUE THREAD

**Issue by DiegoGuidaF** [Skycoder42/qsshfs#1]
Hi,
I have just tried compiling it and it fails.
Missing "dialogmaster.h" file imported from "mainwindow.cpp".

Could you please include it?

Thank you!

**Comment by Skycoder42** [comment]
It is already there, as *qpm dependency* You will have to install [qpm](https://github.com/Cutehacks/qpm) and run `qpm install` in the project root folder to get the sources.

Please note that I am currently replacing qpm by [qpmx](https://github.com/Skycoder42/qpmx), which means for a future release, qpmx will be needed as well.

I will keep this issue open until then, to remember to update the README
