### ISSUE TITLE
Mount operation fails

### ISSUE THREAD

**Issue by Snogard** [Skycoder42/qsshfs#4]
OS: Archlinux

Error: The SSH_ASKPASS environment variable must be set!
You can use for example "ksshaskpass"

if you need more info just ask

**Comment by Skycoder42** [comment]
well, you need to set the `SSH_ASKPASS` environment variable to an askpass tool of your choice. For example, you can install `ksshaskpass` and set the environment variable accordingly.

```bash
export SSH_ASKPASS=ksshaskpass
```

**Comment by Snogard** [comment]
```
export SSH_ASKPASS=ksshaskpass
qsshfs
```
if i do that from the cli i can mount, but the password is requested from the cli and not from ksshaskpass.

modifing the original desktop file by adding "SSH_ASKPASS=ksshaskpass" before the command makes the program ask me the password from the gui.

is there a way i can set that variable without modifying  the original desktop file?

**Comment by Skycoder42** [comment]
you can add it to your .bashrc or .zshrc or whatever you are using

**Comment by Snogard** [comment]
forgot to respond to this but i found out it works better if i let systemd set the env for the system, that way it works even when launching from a desktop file
